package test;

import org.junit.Test;

import com.alibaba.fastjson.JSONObject;
import com.toolkit.entity.DeviceAlter;

public class DeviceAlterTest {
    @Test
    public void test1() {
	String json = "{\r\n" + "	\"alters\": [{\r\n" + "		\"alterParams\": [{\r\n"
		+ "			\"enums\": {\"上电\":1,\"下电\":0,\"自动模式\":2},\r\n"
		+ "			\"max\": 2,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"定时区间内继电器1的状态\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\":null,\r\n"
		+ "			\"max\": 23,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"继电器1起始时间小时\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\": null,\r\n"
		+ "			\"max\": 59,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"继电器1起始时间分钟\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\": null,\r\n"
		+ "			\"max\": 23,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"继电器1起始结束小时\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\": null,\r\n"
		+ "			\"max\": 59,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"继电器1起始结束分钟\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\": {\"上电\":1,\"下电\":0,\"自动模式\":2},\r\n"
		+ "			\"max\": 2,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"定时区间内继电器2的状态\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\":null,\r\n"
		+ "			\"max\": 23,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"继电器2起始时间小时\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\": null,\r\n"
		+ "			\"max\": 59,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"继电器2起始时间分钟\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\": null,\r\n"
		+ "			\"max\": 23,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"继电器2起始结束小时\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\": null,\r\n"
		+ "			\"max\": 59,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"继电器2起始结束分钟\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\": {\"上电\":1,\"下电\":0,\"自动模式\":2},\r\n"
		+ "			\"max\": 2,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"定时区间内继电器3的状态\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\":null,\r\n"
		+ "			\"max\": 23,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"继电器3起始时间小时\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\": null,\r\n"
		+ "			\"max\": 59,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"继电器3起始时间分钟\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\": null,\r\n"
		+ "			\"max\": 23,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"继电器3起始结束小时\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\": null,\r\n"
		+ "			\"max\": 59,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"继电器3起始结束分钟\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\": {\"上电\":1,\"下电\":0,\"自动模式\":2},\r\n"
		+ "			\"max\": 2,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"定时区间内继电器4的状态\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\":null,\r\n"
		+ "			\"max\": 23,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"继电器4起始时间小时\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\": null,\r\n"
		+ "			\"max\": 59,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"继电器4起始时间分钟\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\": null,\r\n"
		+ "			\"max\": 23,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"继电器4起始结束小时\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\": null,\r\n"
		+ "			\"max\": 59,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"继电器4起始结束分钟\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\": {\"上电\":1,\"下电\":0},\r\n"
		+ "			\"max\": 1,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"继电器1默认的遥控状态\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\": {\"上电\":1,\"下电\":0},\r\n"
		+ "			\"max\": 1,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"继电器2默认的遥控状态\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\": {\"上电\":1,\"下电\":0},\r\n"
		+ "			\"max\": 1,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"继电器3默认的遥控状态\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		},{\r\n" + "			\"enums\": {\"上电\":1,\"下电\":0},\r\n"
		+ "			\"max\": 1,\r\n" + "			\"min\": 0,\r\n"
		+ "			\"paramName\": \"继电器4默认的遥控状态\",\r\n"
		+ "			\"paramType\": \"int\",\r\n" + "			\"value\": \"\"\r\n"
		+ "		}],\r\n" + "		\"cmd\": \"D0FB\"\r\n" + "	}],\r\n"
		+ "	\"typeId\": 73,\r\n" + "	\"version\": 113\r\n" + "}";
	DeviceAlter alter=JSONObject.parseObject(json,DeviceAlter.class);
	System.out.println(alter);
    }
}
